### ISSUE TITLE
configure subdomain

### ISSUE THREAD

**Issue by guolijun** [a-chacon/oas_rails#1] opened 2024-07-30 02:57 UTC
Can we configure subdomain?

routes:
```
constraints subdomain: 'api' do
  resources :projects
end
```

**Comment by a-chacon** [comment] 2024-07-30 16:38
Hi! I am glad that you are interested in the project. I didn't try mounting the engine in a subdomain. Did you?. 

I think it should not be a problem. You can try it like this:

```
constraints subdomain: 'api' do
  mount OasRails::Engine => '/docs'
  resources :projects
end
```
If you have an error or an unexpected behavior, then come back with the trace or expected behavior, in another Issue. I will close this because it don't describe an issue or feature request.

**Closed by a-chacon** 2024-07-30 16:38 UTC
